### PR TITLE
Try Heaters out with simple TE and TM MZI circuits

### PR DESCRIPTION
**Pull request by boy4429856821**

### CODE REVIEW

**Comment by boy4429856821** [comment]
only concern that I think is a problem is having multiple ports on the heaters (for example, elec_TEMZIa_G and elec_TEMZIb_G). Is this okay? I want to take measurement repeatability and this is the only way I could think of.... Let me know your thoughts

**Comment by JymBone5** [comment]
That should be okay, if your device has two different input ports but the same electrical pads please name the ports (each something different as you wrote in your question) and then add two labels to the top most pad of the electrical one for each input port, if no electrical pads there will be no issue

**Comment by boy4429856821** [comment]
yup, I believe I have that correct in this design.

**Comment by boy4429856821** [comment]
Also, I'm sort of confused about the creating the .yaml file for this design. Where can I find the .exe file to create the TestParameters yaml file?

**Comment by lukasc-ubc** [comment]
Good timing.  We just updated the instructions and the Yaml creator:

Details on the [Yaml SiEPIC test creator GUI](https://docs.google.com/presentation/d/1HXdqyqy5vN7JVm1cSUt2AW7CwgPD6p_se1ajgKRmObs/edit#slide=id.g2dfc1050e12_0_396)

**Comment by lukasc-ubc** [comment]
Could you please create the Yaml file and upload together with the layout?

**Comment by boy4429856821** [comment]
> Good timing. We just updated the instructions and the Yaml creator:
> 
> Details on the [Yaml SiEPIC test creator GUI](https://docs.google.com/presentation/d/1HXdqyqy5vN7JVm1cSUt2AW7CwgPD6p_se1ajgKRmObs/edit#slide=id.g2dfc1050e12_0_396)

Hi, I tried the yaml_testcreator but it's having issues extracting electrical coordinates, even for the example in the GITHUB repo. Can you check to see if this is reproduced? 
image

**Comment by lukasc-ubc** [comment]
To make feature requests / bugs, can you please use this? https://github.com/SiEPIC/SiEPIC_testcreator/issues

I reported it: https://github.com/SiEPIC/SiEPIC_testcreator/issues/9

**Comment by PetervandenDoel** [comment]
@boy4429856821 Can you try labelling your electrical pad names without the _G at the end?

**Comment by boy4429856821** [comment]
unsure what the errors are....

**Comment by lukasc-ubc** [comment]
You only have one opt_in label, but two separate optical circuits.  Only one of them will be measured (the top one). Please add.

**Comment by boy4429856821** [comment]
Hi @lukasc-ubc , I think my files are passing but there are some other files that were submitted but other users that are causing errors? Please let me know.

**Comment by lukasc-ubc** [comment]
Great!

**Pull request merged**
