### PR TITLE
Submission 1 WDM Filter 2 Stage

### PR DESCRIPTION
**Pull request by surya-karmakar**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Is there a problem with the YAML file?  @PetervandenDoel @JymBone5 

```
Running verification on EBeam_heaters_commlab_studentWDMfilter2stage.yaml
Traceback (most recent call last):
  File "/home/runner/work/openEBL-2024-07-Si-Heaters/openEBL-2024-07-Si-Heaters/run_yaml_verification.py", line 18, in <module>
    print(' - number of routines: %s' % len(yaml_data['Routines']))
KeyError: 'Routines'
Error: Process completed with exit code 1.

```

**Comment by JymBone5** [comment]
Is this an older yaml file? I think the term Routine was changed to sequence awhile ago

**Comment by JymBone5** [comment]
Send the file and I'll fix it

**Comment by surya-karmakar** [comment]
Is there anything needed from my side?

**Comment by lukasc-ubc** [comment]
The Routine error was an automated verification based on the previous YAML format.
Layout looks good to merge.

**Pull request merged**
