### PR TITLE
Global optimized SWG to strip

### PR DESCRIPTION
**Pull request by SK747**
Just some passive devices for possible future publication on global opt devices

### CODE REVIEW

**Comment by SK747** [comment]
no EO testing is necessary

**Comment by lukasc-ubc** [comment]
Please put all your Si geometries on the Si layer.  See the layer table in the Readme file.  Your taper won't get manufactured as is:

image

**Comment by SK747** [comment]
Sorry about that Lukas. I didnt notice. I fixed them

**Comment by lukasc-ubc** [comment]
Unfortunately your layout size is incorrect.  So I have to revert the commit.  Please submit on the next run.

image

**Comment by lukasc-ubc** [comment]
I fixed it for you.

**Comment by SK747** [comment]
Thanks a lot! Very sorry about that.

**Pull request merged**
